name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push Docker container to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          docker build -t shayan704/redoproject .
          docker tag shayan704/redoproject registry.render.com/mlprojectredo/shayan704/redoproject:latest
          docker push registry.render.com/mlprojectredo/shayan704/redoproject:latest
          
          # Deploy using Render CLI
          curl -L https://github.com/renderinc/render-cli/releases/download/v0.1.9/render -o /usr/local/bin/render
          chmod +x /usr/local/bin/render
          render login --api-key $RENDER_API_KEY
          render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }} --dockerfile ./Dockerfile
