name: Build and deploy container app to Render - studentperformancecheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push container image to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          docker build -t redo_studentpred .
          docker tag redo_studentpred registry.render.com/mlprojectredo/redo_studentpred:latest
          docker push registry.render.com/mlprojectredo/redo_studentpred:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -L https://github.com/renderinc/render-cli/releases/download/v0.1.9/render -o /usr/local/bin/render
          chmod +x /usr/local/bin/render
          render login --api-key $RENDER_API_KEY
          render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }} --dockerfile ./Dockerfile
